{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOexZpws4vOTcN4QP46Mest"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "import random\n",
        "from datetime import datetime\n",
        "\n",
        "class Account:\n",
        "    def __init__(self, balance=0, pin=\"1234\"):\n",
        "        self.balance = balance\n",
        "        self.pin = pin\n",
        "        self.transaction_history = []\n",
        "\n",
        "    def check_pin(self, entered_pin):\n",
        "        return entered_pin == self.pin\n",
        "\n",
        "    def deposit(self, amount):\n",
        "        self.balance += amount\n",
        "        self.transaction_history.append((datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"), f\"Deposited: KES {amount:.2f}\"))\n",
        "\n",
        "    def withdraw(self, amount):\n",
        "        if amount > self.balance:\n",
        "            raise ValueError(\"Insufficient funds\")\n",
        "        self.balance -= amount\n",
        "        self.transaction_history.append((datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"), f\"Withdrawn: KES {amount:.2f}\"))\n",
        "\n",
        "    def change_pin(self, new_pin):\n",
        "        if len(new_pin) != 4 or not new_pin.isdigit():\n",
        "            raise ValueError(\"PIN must be 4 digits\")\n",
        "        self.transaction_history.append((datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"), \"PIN Changed\"))\n",
        "        self.pin = new_pin\n",
        "\n",
        "    def get_transaction_history(self):\n",
        "        return self.transaction_history\n",
        "\n",
        "def format_money(amount):\n",
        "    return f\"KES {amount:.2f}\"\n",
        "\n",
        "def main():\n",
        "    account = Account()\n",
        "    while True:\n",
        "        print(\"\\n=== M-Pesa Menu ===\")\n",
        "        print(\"1. Deposit\")\n",
        "        print(\"2. Withdraw\")\n",
        "        print(\"3. Check Balance\")\n",
        "        print(\"4. Manage PIN\")\n",
        "        print(\"5. View Transactions\")\n",
        "        print(\"6. Exit\")\n",
        "\n",
        "        choice = input(\"Choose an option (1-6): \")\n",
        "\n",
        "        match choice:\n",
        "            case \"1\":  # Deposit\n",
        "                try:\n",
        "                    amount = float(input(\"How much would you like to deposit? \"))\n",
        "                    if amount <= 0:\n",
        "                        raise ValueError(\"Please enter a positive amount.\")\n",
        "                    pin = input(\"Please enter your PIN: \")\n",
        "                    if account.check_pin(pin):\n",
        "                        account.deposit(amount)\n",
        "                        print(f\"Success! {format_money(amount)} has been deposited. Your new balance is {format_money(account.balance)}.\")\n",
        "                    else:\n",
        "                        print(\"Oops! That PIN doesn't seem to match. Try again.\")\n",
        "                except ValueError as e:\n",
        "                    print(f\"Whoops! {e}\")\n",
        "\n",
        "            case \"2\":  # Withdraw\n",
        "                try:\n",
        "                    amount = float(input(\"How much would you like to withdraw? \"))\n",
        "                    if amount <= 0:\n",
        "                        raise ValueError(\"Please enter a positive amount.\")\n",
        "                    pin = input(\"Please enter your PIN: \")\n",
        "                    if account.check_pin(pin):\n",
        "                        account.withdraw(amount)\n",
        "                        print(f\"Success! You've withdrawn {format_money(amount)}. Your new balance is {format_money(account.balance)}.\")\n",
        "                    else:\n",
        "                        print(\"Oops! That PIN doesn't seem to match. Try again.\")\n",
        "                except ValueError as e:\n",
        "                    print(f\"Whoops! {e}\")\n",
        "\n",
        "            case \"3\":  # Balance Inquiry\n",
        "                pin = input(\"Please enter your PIN to check your balance: \")\n",
        "                if account.check_pin(pin):\n",
        "                    print(f\"Your current balance is: {format_money(account.balance)}\")\n",
        "                else:\n",
        "                    print(\"Oops! That PIN doesn't seem to match. Try again.\")\n",
        "\n",
        "            case \"4\":  # PIN Management\n",
        "                pin = input(\"Please enter your current PIN: \")\n",
        "                if account.check_pin(pin):\n",
        "                    new_pin = input(\"Enter your new PIN (4 digits): \").strip()\n",
        "                    try:\n",
        "                        account.change_pin(new_pin)\n",
        "                        print(\"Your PIN has been changed successfully!\")\n",
        "                    except ValueError as e:\n",
        "                        print(f\"Whoops! {e}\")\n",
        "                else:\n",
        "                    print(\"Oops! That PIN doesn't seem to match. Try again.\")\n",
        "\n",
        "            case \"5\":  # Transaction History\n",
        "                pin = input(\"Please enter your PIN to view transactions: \")\n",
        "                if account.check_pin(pin):\n",
        "                    history = account.get_transaction_history()\n",
        "                    if history:\n",
        "                        print(\"\\nYour transactions:\")\n",
        "                        for date, transaction in history:\n",
        "                            print(f\"  - {date} - {transaction}\")\n",
        "                    else:\n",
        "                        print(\"You haven't made any transactions yet.\")\n",
        "                else:\n",
        "                    print(\"Oops! That PIN doesn't seem to match. Try again.\")\n",
        "\n",
        "            case \"6\":  # Exit\n",
        "                print(\"Thanks for using M-Pesa. Have a great day!\")\n",
        "                break\n",
        "\n",
        "            case _:\n",
        "                print(\"Sorry, that's not a valid option. Please try again.\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ozKciS3eIWlV",
        "outputId": "2241a069-557b-44b1-a050-2d3cbe87cfa6"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "=== M-Pesa Menu ===\n",
            "1. Deposit\n",
            "2. Withdraw\n",
            "3. Check Balance\n",
            "4. Manage PIN\n",
            "5. View Transactions\n",
            "6. Exit\n",
            "Choose an option (1-6): 1\n",
            "How much would you like to deposit? 1000\n",
            "Please enter your PIN: 1234\n",
            "Success! KES 1000.00 has been deposited. Your new balance is KES 1000.00.\n",
            "\n",
            "=== M-Pesa Menu ===\n",
            "1. Deposit\n",
            "2. Withdraw\n",
            "3. Check Balance\n",
            "4. Manage PIN\n",
            "5. View Transactions\n",
            "6. Exit\n",
            "Choose an option (1-6): 3\n",
            "Please enter your PIN to check your balance: 3\n",
            "Oops! That PIN doesn't seem to match. Try again.\n",
            "\n",
            "=== M-Pesa Menu ===\n",
            "1. Deposit\n",
            "2. Withdraw\n",
            "3. Check Balance\n",
            "4. Manage PIN\n",
            "5. View Transactions\n",
            "6. Exit\n",
            "Choose an option (1-6): 3\n",
            "Please enter your PIN to check your balance: 35\n",
            "Oops! That PIN doesn't seem to match. Try again.\n",
            "\n",
            "=== M-Pesa Menu ===\n",
            "1. Deposit\n",
            "2. Withdraw\n",
            "3. Check Balance\n",
            "4. Manage PIN\n",
            "5. View Transactions\n",
            "6. Exit\n",
            "Choose an option (1-6): 5\n",
            "Please enter your PIN to view transactions: 1234\n",
            "\n",
            "Your transactions:\n",
            "  - 2025-01-30 16:53:51 - Deposited: KES 1000.00\n",
            "\n",
            "=== M-Pesa Menu ===\n",
            "1. Deposit\n",
            "2. Withdraw\n",
            "3. Check Balance\n",
            "4. Manage PIN\n",
            "5. View Transactions\n",
            "6. Exit\n"
          ]
        }
      ]
    }
  ]
}